[package]
name = "gljam"
version = "0.1.0"
authors = ["yashin-alexander <yashin.alexander.42@gmail.com>"]

[dependencies]
cgmath = "0.16.1"
glfw = "0.23.0"
image = "0.19.0"
gl = "0.10.0"
tobj = "0.1.6"
